"""create Winners model

Revision ID: 1f782b1dc135
Revises: cbf2304f0ac4
Create Date: 2024-02-08 02:20:16.115510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f782b1dc135'
down_revision: Union[str, None] = 'cbf2304f0ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winners',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('word', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('winners_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_winners_users', 'users', 'winners', ['winners_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winners')
    op.drop_constraint('fk_winners_users', 'users', type_='foreignkey')
    op.drop_column('users', 'winners_id')

    # ### end Alembic commands ###
